objects/GeEL_Exception__c.object
<CustomObject>
    <description>Used to capture Exceptions within the System</description>
    <fields>
        <fullName>Custom_Exception_Message__c</fullName>
        <description>Custom Exception Message that was used by the class</description>
        <label>Custom Exception Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_ID__c</fullName>
        <description>The Id of the record that caused the issue if known / was not being processed as part of a list</description>
        <label>Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Body__c</fullName>
        <description>The body of the web service request which caused the exception</description>
        <label>Request Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Body__c</fullName>
        <description>The response returned in the web service which caused the exception</description>
        <label>Response Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status_Code__c</fullName>
        <description>The status code returned (if the exception was caused by a web service)</description>
        <label>Status Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_of_origin__c</fullName>
        <defaultValue>&quot;Salesforce&quot;</defaultValue>
        <description>Used to determine the system of origin</description>
        <label>System of origin</label>
        <picklist>
            <picklistValues>
                <fullName>Salesforce</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Web_Service_Method__c</fullName>
        <description>The web service method which was used when the exception occurred (e.g. GET, POST, PUT, PATCH</description>
        <label>Web Service Method</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Exception</label>
    <nameField>
        <displayFormat>Exp-{000000}</displayFormat>
        <label>Exception Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <recordTypes>
        <fullName>Web_Service</fullName>
        <active>true</active>
        <description>Used for Web Service Specific Exceptions</description>
        <label>Web Service</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GeWS_WebServiceException_EH.cls
/******************************************************************
 Name:  GeWS_WebServiceException_EH
 Copyright © 2017
 ======================================================
======================================================
Purpose:  Generic web service exception
-------                                                             
======================================================
======================================================
History                                                            
-------                                                            
VERSION      AUTHOR                DATE             DETAIL             Description
   1.0    	Mark Cook 		    21/08/2017          
***********************************************************************/
public with sharing class GeWS_WebServiceException_EH extends GeEF_ExceptionHandler_A {

    /*******************************************************************
    * @description XXXX
    * @param  String theSource - The class and method source of exception
    * @param  GeWS_WebService_A.CallOutResults wsException - Callout results object
    * @param  Exception e - The exception that has been thrown
    * @param  String recordID - the record id related to the exception or record being processed
    * @param  String exceptionMessage - the exception message
    * @return VOID
    * @Throws [Exceptions]: None                                                 
    ********************************************************************/
	public GeWS_WebServiceException_EH (  String theSource
										, GeWS_WebService_A.CallOutResults wsException
										, Exception e
										, String recordID
										, String exceptionMessage){
		super.populateBaseExceptionObject(theSource, wsException.errorMessage, e);
		addExceptionDetails(recordID, wsException, exceptionMessage);

		processExceptions();
	}


    /*******************************************************************
    * @description XXXX
    * @param  String theSource - The class and method source of exception
    * @param  GeWS_WebService_A.CallOutResults wsException - Callout results object
    * @param  String recordID - the record id related to the exception or record being processed
    * @param  String exceptionMessage - the exception message
    * @return VOID
    * @Throws [Exceptions]: None                                                 
    ********************************************************************/
	public GeWS_WebServiceException_EH(   String theSource
										, GeWS_WebService_A.CallOutResults wsException
										, String recordID
										, String exceptionMessage){
		try {
			throw new GeEF_Exception('Standard Web Service Exception');
		} catch (Exception e){

			super.populateBaseExceptionObject(theSource, wsException.errorMessage, e);
			addExceptionDetails(recordID, wsException, exceptionMessage);
			processExceptions();
		}
		
	}
    /*******************************************************************
    * @description Populates the exception message with specific details
    *			   relating to this process
    * @param  String recordID - the record id
    * @param  GeWS_WebService_A.CallOutResults wsException - Callout results object
    * @param  String exceptionMessage - the exception message
    * @return VOID
    * @Throws [Exceptions]: None                                                 
    ********************************************************************/
	private void addExceptionDetails(  String recordID
									 , GeWS_WebService_A.CallOutResults wsException
									 , String exceptionMessage){

		instanceOfException.RecordtypeId = Ge_CommonUtility_U.getSObjectRecordTypeId(GeEL_Exception__c.sObjectType
																					, 'Web_Service' );
		instanceOfException.System_of_origin__c = 'Salesforce';
		instanceOfException.Record_ID__c = recordID;
		instanceOfException.Web_Service_Method__c = wsException.requestMethod;
		instanceOfException.Status_Code__c = String.valueOf(wsException.statusCode);
		instanceOfException.Request_Body__c = wsException.requestBody;
		instanceOfException.Response_Body__c = wsException.body;
		instanceOfException.Custom_Exception_Message__c = exceptionMessage;

	}

    /*******************************************************************
    * @description Processes the new exception record
    * @return VOID
    * @Throws [Exceptions]: None                                                 
    ********************************************************************/
	public override void processExceptions() {
		super.createExceptionRecord(false);
	}
}